// Global Configuration File
// Generated by Config Tool
const CALENDAR_CONFIG = {
    "apiKey": "AIzaSyA3GRJ6eD0DSVkk0eblWxvNAspvELfEXPU",
    "calendarId": "psjq9llj3ss5k3mqupp8f2vj7blan3ha@import.calendar.google.com",
    "mapping": {
        "title": "summary",
        "description": "",
        "location": "location",
        "start": "start.dateTime",
        "end": "end.dateTime"
    },
    "textFilter": [
        "@ Pleasant Township Fire Department"
    ]
};